### ISSUE TITLE
SocketRocket vs CocoaAsyncSocket

### ISSUE THREAD

**Issue by bigtreenono** [lzwjava/Keynotes#1]
Hi, 您好
我对 socket 不太了解, 所以请问下
1. SocketRocket 与 CocoaAsyncSocket 这两个库的区别是 ?
2. 可以麻烦您提供一些 iOS 开发中学习 socket 编程有哪些参考资料或书籍吗 ?

感谢.

**Comment by lzwjava** [comment]
1. 对 CocoaAsyncSocket 不太了解。感觉上是 TCP 的一个库。 SocketRocket 则是 WebSocket 协议的一个实现。 SocketRocket 底层采用 TCP 连接，所以 SocketRocket 更上层一些。
2. WebSocket RFC 可以读读， https://tools.ietf.org/html/rfc6455 ，给自己一个星期，还是可以读下来的。宜龙的文章也可以参考下，[《大话 Socket》](https://github.com/ChenYilong/iOSBlog/blob/master/Tips/%E5%A4%A7%E8%AF%9DSocket.md)。书籍这方面的我还没读过。: ( 

读书去…

**Comment by bigtreenono** [comment]
谢谢
